### ISSUE TITLE
Official site blank

### ISSUE THREAD

**Issue by lucasjinreal** [modular/modular#16] opened 2023-05-04 04:54 UTC
![image](https://user-images.githubusercontent.com/21303438/236115410-330395cf-e41a-4b8e-badb-2f97ee95e19a.png)

**Comment by iamtimdavis** [comment] 2023-05-04 05:04
Thanks Lucas - can't reproduce that. Can you please give us some more details - modular.com/get-started is working. Also make sure to accept our cookies if you haven't already ?

**Comment by lucasjinreal** [comment] 2023-05-04 06:30
@iamtimdavis does the website not accessable in China?

**Comment by goldiegadde** [comment] 2023-05-05 03:23
@lucasjinreal can you try with a different browser and see if it works. No one has run into this issue, so I am inclined to close this one, but let us know, will keep it open for another day!

**Closed as completed** 2023-05-05 17:33 UTC
Labels: mojo, mojo-repo
